export const SERVICE_SLUGS = [
  "signaletique",
  "logo-3d",
  "logo-inox",
  "totem-publicitaire",
  "habillage-facade",
  "palissade-chantier",
  "impression-grand-format",
  "menuiserie-aluminium",
  "maintenance",
] as const;

export type ServiceSlug = (typeof SERVICE_SLUGS)[number];

export const SERVICES_CONFIG: Record<
  ServiceSlug,
  { icon: string; color: string; translationKey: string }
> = {
  signaletique: { icon: "🔷", color: "#1e3a8a", translationKey: "signaletique" },
  "logo-3d": { icon: "🔶", color: "#e63946", translationKey: "logo3d" },
  "logo-inox": { icon: "⬜", color: "#475569", translationKey: "logoInox" },
  "totem-publicitaire": { icon: "📍", color: "#0891b2", translationKey: "totemPublicitaire" },
  "habillage-facade": { icon: "🏗️", color: "#7c3aed", translationKey: "habillage" },
  "palissade-chantier": { icon: "🚧", color: "#d97706", translationKey: "palissade" },
  "impression-grand-format": { icon: "🖨️", color: "#059669", translationKey: "impression" },
  "menuiserie-aluminium": { icon: "🔩", color: "#64748b", translationKey: "menuiserie" },
  maintenance: { icon: "🔧", color: "#be185d", translationKey: "maintenance" },
};

export const PORTFOLIO_PROJECTS = [
  {
    id: 1,
    title: "Enseigne Lumineux – Centre Commercial",
    client: "Mall Express",
    location: "Tanger",
    year: 2024,
    category: "signaletique",
    image: "/images/portfolio/project-1.jpg",
    color: "#1e3a8a",
  },
  {
    id: 2,
    title: "Logo 3D Aluminium – Siège Social",
    client: "Maroc Finance",
    location: "Casablanca",
    year: 2024,
    category: "logo",
    image: "/images/portfolio/project-2.jpg",
    color: "#e63946",
  },
  {
    id: 3,
    title: "Habillage Façade – Boutique Mode",
    client: "Élégance Boutique",
    location: "Rabat",
    year: 2023,
    category: "facade",
    image: "/images/portfolio/project-3.jpg",
    color: "#7c3aed",
  },
  {
    id: 4,
    title: "Totem Publicitaire – Hôtel 5★",
    client: "Royal Atlas Hotel",
    location: "Agadir",
    year: 2024,
    category: "totem",
    image: "/images/portfolio/project-4.jpg",
    color: "#0891b2",
  },
  {
    id: 5,
    title: "Impression Grand Format – Événement",
    client: "SIAM 2024",
    location: "Meknès",
    year: 2024,
    category: "impression",
    image: "/images/portfolio/project-5.jpg",
    color: "#059669",
  },
  {
    id: 6,
    title: "Signalétique Directionnelle",
    client: "CHU Tanger",
    location: "Tanger",
    year: 2023,
    category: "signaletique",
    image: "/images/portfolio/project-6.jpg",
    color: "#1e3a8a",
  },
  {
    id: 7,
    title: "Logo Inox – Clinique Privée",
    client: "Clinique Al Amal",
    location: "Fès",
    year: 2023,
    category: "logo",
    image: "/images/portfolio/project-7.jpg",
    color: "#475569",
  },
  {
    id: 8,
    title: "Palissade Publicitaire – Résidence",
    client: "Jardins du Détroit",
    location: "Tanger",
    year: 2024,
    category: "facade",
    image: "/images/portfolio/project-8.jpg",
    color: "#d97706",
  },
  {
    id: 9,
    title: "Menuiserie Aluminium – Showroom",
    client: "BMW Maroc",
    location: "Casablanca",
    year: 2023,
    category: "signaletique",
    image: "/images/portfolio/project-9.jpg",
    color: "#64748b",
  },
];

export const CLIENT_LOGOS = [
  { name: "Marjane", abbr: "MJ" },
  { name: "Attijariwafa Bank", abbr: "AW" },
  { name: "Orange Maroc", abbr: "OR" },
  { name: "ONCF", abbr: "ON" },
  { name: "Lydec", abbr: "LY" },
  { name: "Tanger Med", abbr: "TM" },
  { name: "Société Générale", abbr: "SG" },
  { name: "Al Omrane", abbr: "AO" },
];
